---
title: "Assignment_Wk3"
author: "Hong Fan"
date: "12/25/2016"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
## U.S. Per Capita Income in 1975
```{r, message=FALSE,warning=FALSE, echo=FALSE}
library(plotly)
state_income <- data.frame(State = state.abb, Income = as.vector(state.x77[,2]))
state_income$hover <- with(state_income, paste(State, '<br>', "Income:", Income))
borders <- list(color = toRGB("black"))
map_options <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showlakes = TRUE,
  lakecolor = toRGB("blue")
)
plot_ly(state_income, z = state_income$Income, text = state_income$hover, locations =        state_income$State, type = 'choropleth', locationmode = "USA-states", color = state_income$Income, colors = 'Purples',          marker = list(line = borders)) %>%
layout(title = 'US Income Per Capita in 1975', geo = map_options)
```

## Illiteracy vs Murder Rates in 50 U.S. States
```{r, message=FALSE,warning=FALSE, echo=FALSE}
library(plotly)
Illiteracy = state.x77[, "Illiteracy"]
Murder = state.x77[,"Murder"]
plot_ly(as.data.frame(state.x77), x = Illiteracy, y = Murder, mode = "markers") %>%
  layout(title = "Illiteracy and Murder Rates in 50 U.S. States",
         xaxis = list(title = "Illiteracy (Percent of population)", showgrid = F),
         yaxis = list(title = "Murder Rates (per 100,000 population)", showgrid = F))
```

